language: go

go:
    - "1.16"
    - "1.17"
    - "1.18"

before_install:
    - go install github.com/mattn/goveralls@latest

before_script:
    - mkdir -p /tmp/redis6379 /tmp/redis6380 /tmp/redis6381
    - cd /tmp/redis6379
    - redis-server --port 6379 &
    - cd /tmp/redis6380
    - redis-server --port 6380 &
    - cd /tmp/redis6381
    - redis-server --port 6381 &
    - cd ${TRAVIS_BUILD_DIR}

script:
    - ./test.sh
    - $GOPATH/bin/goveralls -service=travis-ci
